image: freebsd
packages:
  - go
sources:
  - https://github.com/dbalan/cryptopals
tasks:
  - cryptopals: |
     mkdir -p go/src/github.com/dbalan
     mv cryptopals go/src/github.com/dbalan/
     cd go/src/github.com/dbalan/cryptopals/
     go get -v ./...
     go get -v -t ./...
     go test -v ./...



